spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GeoChase_Db
    username: postgres
    password: 1234 # Kendi PostgreSQL ?ifreni yazmay? unutma!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Java s?n?flar?m?z? otomatik olarak tablolara dönü?türür
    show-sql: true     # Arka planda çal??an SQL kodlar?n? konsolda görmemizi sa?lar
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080 # Spring Boot uygulamam?z?n çal??aca?? port